### ISSUE TITLE
Reverse SRAS Support?

### ISSUE THREAD

**Issue by hack13** [ft-/phpGridServer#4]
I was wondering if you were planning on reverse support for how SRAS stores assets? If not, I might consider forking and adding that support, so grids like many I host since SRAS has come out now official abandoned, I would like to help make for my clients as well as people out in the metaverse using SRAS a way to keep storing their assets the way they are but move to a PHP front-end.

The only reason I bring this up, is because even with the new "XAssets" feature that contains de-duplication we are still dumping raw blobs into a database and that's just not a clean way to store tons of assets. They should be stored as files, well at least that's how I feel.

**Comment by ft-** [comment]
the idea of putting blobs is only being told to be bad. Actually, MySQL has a certain support that is specific for storing blobs out of table storage. But this was done definitely wrong on XAssets.
Just noticed that request right now.
