### ISSUE TITLE
i got some issues with the precense service

### ISSUE THREAD

**Issue by fine77** [ft-/phpGridServer#5]
no sim will be registered within the presence.
the error handler of php told me the following.
--
[Wed Oct 21 16:22:57.503673 2015] [:error] [pid 11892] [client XXXXX:65346] PHP Notice:  Login Error: key Could not launch agent at destination. Failed to verify user presence in the grid for Test User, access denied to region sim_test1. in /$WWWPATH/login/login_to_simulator.php on line 95
[Wed Oct 21 16:22:57.503677 2015] [:error] [pid 11892] [client XXXXX:65346] PHP Stack trace:
[Wed Oct 21 16:22:57.503681 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   1. {main}() /$WWWPATH/index.php:0
[Wed Oct 21 16:22:57.503685 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   2. require_once() /$WWWPATH/index.php:19
[Wed Oct 21 16:22:57.503689 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   3. require() /$WWWPATH/xmlrpc/xmlrpc.php:61
[Wed Oct 21 16:22:57.503693 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   4. require() /$WWWPATH/xmlrpc/xmlrpc_login_to_simulator.php:13
[Wed Oct 21 16:22:57.503703 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   5. LoginFailResponse($reason = 'key', $message = 'Could not launch agent at destination. Failed to verify user presence in the grid for Test User, access denied to region sim_test1.') /$WWWPATH/login/login_to_simulator.php:471
[Wed Oct 21 16:22:57.503711 2015] [:error] [pid 11892] [client XXXXX:65346] PHP   6. trigger_error('Login Error: key Could not launch agent at destination. Failed to verify user presence in the grid for Test User, access denied to region sim_test1.') /$WWWPATH/login/login_to_simulator.php:95
--

the sim can't be registered. got the error:
--
17:14:48 - [FORMS]: Error receiving response from http://XXXXX:8002/grid: The remote server returned an error: (500) Internal Server Error.. Request: SCOPEID=00000000-0000-0000-0000-000000000000&REGIONID=82a57dcf-fe40-44eb-aec3-575c89941e65&METHOD=get_neighbours
17:14:48 - [GRID CONNECTOR]: Exception when contacting grid server at http://XXXXX:8002/grid: The remote server returned an error: (500) Internal Server Error.
--

haven't found a solution yet. i'm using Apache 2.4.7 and php 5.5.9 from the official ubuntu 14.04 repository.

i hope someone can tell me how to fix that issue.

**Comment by fine77** [comment]
sorry i've posted the wrong error

[Wed Oct 21 14:29:07.065129 2015] [:error] [pid 11048] [client XXXXX:58697] PHP Strict standards:  Only variables should be passed by reference in /$WWWPATH/lib/connectors/db/mysql/PresenceService.php on line 212
[Wed Oct 21 14:29:07.065161 2015] [:error] [pid 11048] [client XXXXX:58697] PHP Stack trace:
[Wed Oct 21 14:29:07.065168 2015] [:error] [pid 11048] [client XXXXX:58697] PHP   1. {main}() /$WWWPATH/index.php:0
[Wed Oct 21 14:29:07.065191 2015] [:error] [pid 11048] [client XXXXX:58697] PHP   2. require_once() /$WWWPATH/index.php:19
[Wed Oct 21 14:29:07.065196 2015] [:error] [pid 11048] [client XXXXX:58697] PHP   3. require() /$WWWPATH/xmlrpc/xmlrpc.php:61
[Wed Oct 21 14:29:07.065201 2015] [:error] [pid 11048] [client XXXXX:58697] PHP   4. require() /$WWWPATH/xmlrpc/xmlrpc_login_to_simulator.php:13
[Wed Oct 21 14:29:07.065215 2015] [:error] [pid 11048] [client XXXXX:58697] PHP   5. MySQLPresenceServiceConnector->deletePresenceByAgentUUID($userid = class UUID { private $ID = '21e895dc-99ff-484f-ad3d-9700bc6a81f3' }) /$WWWPATH/login/login_to_simulator.php:343

hope that helps

**Comment by fine77** [comment]
i've found out in the debug that the following isn't defined in the config.acl.php:
    Denied access to method getNeighbours by ACL
trying to fix it. hope it works.

**Comment by fine77** [comment]
i've found the solution.
you only support private ip's for the simulators. that restricts the use of the whole grid.
but i know now how to fix the problem

**Comment by ft-** [comment]
the default ACL is based on IPv4 connects and needs to be SYSTEMIP based due to the checks done. However, the ACL system can be disabled and is now commented in INSTALL.md
