### ISSUE TITLE
inventory issue

### ISSUE THREAD

**Issue by QuillLittlefeather** [ft-/phpGridServer#8]
I keep seeing this non stop on region server when i login 

04:37:01 - [XINVENTORY SERVICES CONNECTOR]: Folder id does not match. Expected f
1a4daaf-bc35-41ab-935c-8f5b3d40a1c4 got 00000000-0000-0000-0000-000000000000

i also upload iar and it will not load my inventory when i login

**Comment by ft-** [comment]
xml output of GETMULTIPLEFOLDERSCONTENT was replacing - with _ when generating the xml tags. OpenSim does not like that.
